name: powershell/PowerShell-CI-macos
on:
  push:
    branches:
      - master
      - release*
      - feature*
    paths:
      - "**"
      - "!.github/ISSUE_TEMPLATE/**"
      - "!.dependabot/config.yml"
      - "!.pipelines/**"
      - "!test/perf/**"
  pull_request:
    branches:
      - master
      - release*
      - feature*
    paths:
      - ".github/actions/**"
      - ".github/workflows/macos-ci.yml"
      - "**.props"
      - build.psm1
      - src/**
      - test/**
      - tools/buildCommon/**
      - tools/ci.psm1
      - "!test/common/markdown/**"
      - "!test/perf/**"

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  FORCE_FEATURE: 'False'
  FORCE_PACKAGE: 'False'
  HOMEBREW_NO_ANALYTICS: 1
  NUGET_KEY: none
  POWERSHELL_TELEMETRY_OPTOUT: 1
  __SuppressAnsiEscapeSequences: 1
  nugetMultiFeedWarnLevel: none
  system_debug: 'false'
jobs:
  ci_build:
    name: Build PowerShell
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 1000
      - name: Build
        uses: "./.github/actions/build/ci"
  macos_test_unelevated_ci:
    name: macos Unelevated CI
    needs: ci_build
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 1000
      - name: macOS Unelevated CI
        uses: "./.github/actions/test/nix"
        with:
          purpose: UnelevatedPesterTests
          tagSet: CI
  macos_test_elevated_ci:
    name: macOS Elevated CI
    needs: ci_build
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 1000
      - name: macOS Elevated CI
        uses: "./.github/actions/test/nix"
        with:
          purpose: ElevatedPesterTests
          tagSet: CI
  macos_test_unelevated_others:
    name: macOS Unelevated Others
    needs: ci_build
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 1000
      - name: macOS Unelevated Others
        uses: "./.github/actions/test/nix"
        with:
          purpose: UnelevatedPesterTests
          tagSet: Others
  macos_test_elevated_others:
    name: macOS Elevated Others
    needs: ci_build
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 1000
      - name: macOS Elevated Others
        uses: "./.github/actions/test/nix"
        with:
          purpose: ElevatedPesterTests
          tagSet: Others
  verify_xunit:
    name: Verify xUnit test results
    needs: ci_build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 1000
      - name: Verify xUnit test results
        uses: "./.github/actions/test/verify_xunit"
  PackageMac-macos_packaging:
    name: macOS packaging (bootstrap only)
    runs-on:
      - macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Bootstrap packaging
      if: success() || failure()
      run: |-
        import-module ./build.psm1
        start-psbootstrap -package
      shell: pwsh
