name: powershell/PowerShell-CI-macos
on:
  push:
    branches:
    - master
    - release*
    - feature*
    paths:
    - "*"
    - "!tools/releaseBuild/**/*"
    - "!.vsts-ci/misc-analysis.yml"
    - "!.github/ISSUE_TEMPLATE/*"
    - "!.github/workflows/*"
    - "!.dependabot/config.yml"
    - "!.pipelines/*"
    - "!test/perf/*"
  pull_request:
    branches:
    - master
    - release*
    - feature*
    paths:
    - "*"
    - "!.dependabot/config.yml"
    - "!.github/ISSUE_TEMPLATE/*"
    - "!.github/workflows/*"
    - "!.vsts-ci/misc-analysis.yml"
    - "!.vsts-ci/windows.yml"
    - "!.vsts-ci/windows/*"
    - "!tools/cgmanifest.json"
    - "!LICENSE.txt"
    - "!test/common/markdown/*"
    - "!test/perf/*"
    - "!tools/packaging/*"
    - "!tools/releaseBuild/*"
    - "!tools/releaseBuild/azureDevOps/templates/*"
    - "!README.md"
    - "!.spelling"
    - "!.pipelines/*"
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  FORCE_FEATURE: 'False'
  FORCE_PACKAGE: 'False'
  HOMEBREW_NO_ANALYTICS: 1
  NUGET_KEY: none
  POWERSHELL_TELEMETRY_OPTOUT: 1
  __SuppressAnsiEscapeSequences: 1
  nugetMultiFeedWarnLevel: none
  system_debug: 'false'
jobs:
  vsts_ci_templates_ci_build:
    name: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_ci_build.yml"
    with:
      pool: macOS-latest
      jobName: mac_build
      displayName: macOS Build
  vsts_ci_templates_nix_test:
    name: vsts_ci_templates_nix_test
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_nix_test.yml"
    with:
      purpose: UnelevatedPesterTests
      tagSet: CI
  vsts_ci_templates_nix_test_2:
    name: vsts_ci_templates_nix_test_2
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_nix_test.yml"
    with:
      purpose: ElevatedPesterTests
      tagSet: CI
  vsts_ci_templates_nix_test_3:
    name: vsts_ci_templates_nix_test_3
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_nix_test.yml"
    with:
      purpose: UnelevatedPesterTests
      tagSet: Others
  vsts_ci_templates_nix_test_4:
    name: vsts_ci_templates_nix_test_4
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_nix_test.yml"
    with:
      purpose: ElevatedPesterTests
      tagSet: Others
  vsts_ci_templates_verify_xunit:
    name: vsts_ci_templates_verify_xunit
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_verify_xunit.yml"
    with:
      pool: macOS-latest
  PackageMac-macos_packaging:
    name: macOS packaging (bootstrap only)
    needs:
    - vsts_ci_templates_ci_build
    runs-on:
      - self-hosted
      - macOS-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/checkout@v4.1.0
    - name: Bootstrap packaging
      if: success() || failure()
      run: |-
        import-module ./build.psm1
        start-psbootstrap -package
      shell: pwsh
